const cardInfo = [
    {code: 'r14', color: 'Red', number: 14, pointValue: 10, img: '/img/r14.png'},
    {code: 'r13', color: 'Red', number: 13, pointValue: 0, img: '/img/r13.png'},
    {code: 'r12', color: 'Red', number: 12, pointValue: 0, img: '/img/r12.png'},
    {code: 'r11', color: 'Red', number: 11, pointValue: 0, img: '/img/r11.png'},
    {code: 'r10', color: 'Red', number: 10, pointValue: 10, img: '/img/r10.png'},
    {code: 'r9', color: 'Red', number: 9, pointValue: 0, img: '/img/r9.png'},
    {code: 'r8', color: 'Red', number: 8, pointValue: 0, img: '/img/r8.png'},
    {code: 'r7', color: 'Red', number: 7, pointValue: 0, img: '/img/r7.png'},
    {code: 'r6', color: 'Red', number: 6, pointValue: 0, img: '/img/r6.png'},
    {code: 'r5', color: 'Red', number: 5, pointValue: 5, img: '/img/r5.png'},
    {code: 'b14', color: 'Black', number: 14, pointValue: 10, img: '/img/b14.png'},
    {code: 'b13', color: 'Black', number: 13, pointValue: 0, img: '/img/b13.png'},
    {code: 'b12', color: 'Black', number: 12, pointValue: 0, img: '/img/b12.png'},
    {code: 'b11', color: 'Black', number: 11, pointValue: 0, img: '/img/b11.png'},
    {code: 'b10', color: 'Black', number: 10, pointValue: 10, img: '/img/b10.png'},
    {code: 'b9', color: 'Black', number: 9, pointValue: 0, img: '/img/b9.png'},
    {code: 'b8', color: 'Black', number: 8, pointValue: 0, img: '/img/b8.png'},
    {code: 'b7', color: 'Black', number: 7, pointValue: 0, img: '/img/b7.png'},
    {code: 'b6', color: 'Black', number: 6, pointValue: 0, img: '/img/b6.png'},
    {code: 'b5', color: 'Black', number: 5, pointValue: 5, img: '/img/b5.png'},
    {code: 'g14', color: 'Green', number: 14, pointValue: 10, img: '/img/g14.png'},
    {code: 'g13', color: 'Green', number: 13, pointValue: 0, img: '/img/g13.png'},
    {code: 'g12', color: 'Green', number: 12, pointValue: 0, img: '/img/g12.png'},
    {code: 'g11', color: 'Green', number: 11, pointValue: 0, img: '/img/g11.png'},
    {code: 'g10', color: 'Green', number: 10, pointValue: 10, img: '/img/g10.png'},
    {code: 'g9', color: 'Green', number: 9, pointValue: 0, img: '/img/g9.png'},
    {code: 'g8', color: 'Green', number: 8, pointValue: 0, img: '/img/g8.png'},
    {code: 'g7', color: 'Green', number: 7, pointValue: 0, img: '/img/g7.png'},
    {code: 'g6', color: 'Green', number: 6, pointValue: 0, img: '/img/g6.png'},
    {code: 'g5', color: 'Green', number: 5, pointValue: 5, img: '/img/g5.png'},
    {code: 'y14', color: 'Yellow', number: 14, pointValue: 10, img: '/img/y14.png'},
    {code: 'y13', color: 'Yellow', number: 13, pointValue: 0, img: '/img/y13.png'},
    {code: 'y12', color: 'Yellow', number: 12, pointValue: 0, img: '/img/y12.png'},
    {code: 'y11', color: 'Yellow', number: 11, pointValue: 0, img: '/img/y11.png'},
    {code: 'y10', color: 'Yellow', number: 10, pointValue: 10, img: '/img/y10.png'},
    {code: 'y9', color: 'Yellow', number: 9, pointValue: 0, img: '/img/y9.png'},
    {code: 'y8', color: 'Yellow', number: 8, pointValue: 0, img: '/img/y8.png'},
    {code: 'y7', color: 'Yellow', number: 7, pointValue: 0, img: '/img/y7.png'},
    {code: 'y6', color: 'Yellow', number: 6, pointValue: 0, img: '/img/y6.png'},
    {code: 'y5', color: 'Yellow', number: 5, pointValue: 5, img: '/img/y5.png'}
];

export { cardInfo };